apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.telemetryService.name }}
spec:
  type: {{ .Values.telemetryService.type }}
  ports:
    - port: {{ .Values.telemetryService.port }}
      targetPort: {{ .Values.telemetryService.targetPort }}
      protocol: {{ .Values.telemetryService.protocol }}
  selector:
    telemetry: {{ include "dragon.telemetryServiceSelector" . }}