apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jupyterService.name }}
spec:
  type: {{ .Values.jupyterService.type }}
  ports:
    - port: {{ .Values.jupyterService.port }}
      targetPort: {{ .Values.jupyterService.targetPort }}
      protocol: {{ .Values.jupyterService.protocol }}
  selector:
    node_index: {{ include "dragon.serviceSelector" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.telemetryService.name }}
spec:
  type: {{ .Values.telemetryService.type }}
  ports:
    - port: {{ .Values.telemetryService.port }}
      targetPort: {{ .Values.telemetryService.targetPort }}
      protocol: {{ .Values.telemetryService.protocol }}
  selector:
    telemetry: {{ include "dragon.telemetryServiceSelector" . }}