# Default values for dragon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

sharedMemoryVolume:
  name: dragonshm
  sizeLimit: 256Gi
  mountPath: /dev/shm

python:
  packages:

pythonPaths:
  - "/inference-service/inference-with-mcp"

frontend:
  labels: {}

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: harbor.greennitrogen.breckenridge.cloud/us-docker.pkg.dev/clean-silo-405421/dragon-sandbox/dragondev
    tag: latest
    pullPolicy: Always

  # This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  workingDir:
  batchName:

  command:
    - /bin/bash
    - "-c"

  args:
    - |
      # which python3;
      # which dragon;
      if [ -f /tmp/requirements.txt ]; then
          python3 -m pip install -r /tmp/requirements.txt;
      fi;
      # python3 -m dragon.cli dragon-config add --ucx-runtime-lib=/usr/lib/x86_64-linux-gnu/ --ucx-include=/usr/include --ucx-build-lib=/usr/lib/x86_64-linux-gnu/;
      dragon --telemetry-level=3 /inference-service/inference-with-mcp/tests/performance_tests/dragon/dragon_performance.py --config_file /inference-service/inference-with-mcp/config_llama_8B.yaml --model_size small --run_type b --num_prompts 2000 --output_dir /inference-service/benchmarks_results/;

  env: {}

  ports:
    - containerPort: 8080

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  rbac:
    create: true

  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}

  # This is for setting Kubernetes Labels to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here:
  # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe: {}
  readinessProbe: {}

  volumes:
    - name: dragon-develop-volume
      persistentVolumeClaim:
        claimName: dragon-develop-pvc
    - name: inference-service-volume
      persistentVolumeClaim:
        claimName: inference-service

  # we assume that volumeMount[0] is the shared filesystem where we host dragon required code such as Batch and the API server
  # and volumeMount[1], when defined, is the user's distinct shared filesystem; unique for each user group
  volumeMounts:
    - name: dragon-develop-volume
      mountPath: /dragon-develop
    - name: inference-service-volume
      mountPath: /inference-service

  nodeSelector:
    node-role.kubernetes.io/service: "true"
    kubernetes.io/hostname: worker-02

  affinity: {}

  tolerations: {}

  jobAnnotations: {}
  jobLabels: {}

  ttlSecondsAfterFinished: 300



backend:
  labels: {}

  nnodes: 1

  image:
    repository: harbor.greennitrogen.breckenridge.cloud/us-docker.pkg.dev/clean-silo-405421/dragon-sandbox/dragondev
    tag: mcp
    pullPolicy: Always

  imagePullSecrets: []

  command:
    - /bin/bash
    - "-c"

  args:
    - |
      if [ -f /tmp/requirements.txt ]; then
          python3 -m pip install -r /tmp/requirements.txt;
      fi;
      # python3 -m dragon.cli dragon-config add --ucx-runtime-lib=/usr/lib/x86_64-linux-gnu/ --ucx-include=/usr/include --ucx-build-lib=/usr/lib/x86_64-linux-gnu/;
      dragon-backend;

  env: {}

  ports:
    - containerPort: 8081
    - containerPort: 4242

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

  rbac:
    create: true

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}

  securityContext:
    allowPrivilegeEscalation: true
    capabilities:
      add:
        - IPC_LOCK
        - IPC_OWNER
        - SYS_RESOURCE
    privileged: true
    readOnlyRootFilesystem: false
    runAsNonRoot: false

  resources:
    limits:
      nvidia.com/gpu: 4
    requests:
      nvidia.com/gpu: 4

  livenessProbe: {}
  readinessProbe: {}

  volumes:
    - name: dragon-develop-volume
      persistentVolumeClaim:
        claimName: dragon-develop-pvc
    - name: inference-service-volume
      persistentVolumeClaim:
        claimName: inference-service

  volumeMounts:
    - name: dragon-develop-volume
      mountPath: /dragon-develop
    - name: inference-service-volume
      mountPath: /inference-service

  nodeSelector:
    node-role.kubernetes.io/compute: "true"

  affinity: {}

  topologySpreadConstraints: {}

  tolerations:
    - key: node-role.kubernetes.io/compute
      operator: Exists
      effect: NoExecute
    - key: nvidia.com/gpu.present
      operator: Exists
      effect: NoSchedule

  jobAnnotations: {}
  jobLabels: {}

  ttlSecondsAfterFinished: 300

jupyterService:
  name: jupyter
  port: 8080
  targetPort: 8080
  protocol: TCP

telemetryService:
  name: telemetry
  type: ClusterIP
  port: 4242
  targetPort: 4242
  protocol: TCP

# For Jupyter notebooks. Set to true when using jupyter.
# this is part of launching a notebook prior to the api server
jupyter:
  enabled: false
  token: ""

# The domain name of the endpoint used for the gateway.
domain:
  name: